"""initial schema

Revision ID: ef6a56f45278
Revises:
Create Date: 2026-02-11 23:20:10.485412

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ef6a56f45278"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
